travis:
  secure:
    BINSTAR_TOKEN: yNzRdoUklS+RJTNo0AgVixPs6gzP3uRnbA65zSwwlDUvamyEOVA+6NGatgAyFeIneHwZ80Ym0mFmYC55NOlO8xfGj41H/2zfKA1X9jvdAx7GjFy+AdzrX3BBG8wmRtcYp3TPzObDsy4m4iI6SUE4c3StVAdmxq+Yr92nO0PqSwqEmUfvDBmAaYFTeWjOD5lN1NdDCNyAMqYi6/l99KZkY6batJiuYmeJbsdQwYlo+5imHQFvTYkdOqqQfUEMBCE6jgf/dBQRC+v97ZtzgZ9i7l6mlqiEOW9Kyn0GvNYhEq3dTSFhA1k5NJrlPKbQ9jBlEqGpNaJSOoILtNp+pcKALH/R6ygliuq/8iOxtXTqTV2aDdEWTga/w2fganETFQd9chgSXLNne/7KOLjVfFYBGLq56tRI2K2qQgS8EPRcYvJ4CyP1b2HcZtomSbY/MKfPNW6/t5RoC71Iu0I7Sy7g813aO8zL5I0dqaq35G6xqYOef+WIFeYX6cLj1rffs5kbljJgAmM6P21nSUuHo3OI/RQf4GhmpwU06Q34hecG+LLo8r4WgdSFBy3sJZMweFU0zSgYAbVQ1Z6wbGtD3whEbc6Cswuqn3a1xOkpfvLriFUH0n3v7A3A8r56eQ1SWieM+hS+t5dTX4eg3Cy+B3kqHFt2QVx0/oNfq6No2D/o630=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
